name: ltb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10|3.11|3.12
  - kvxopt>=1.3.2.1
  - numpy
  - scipy
  - sympy>=1.6,!=1.10.0
  - pandas
  - matplotlib
  - psutil
  - openpyxl
  - andes>=1.9.3
  - pybind11
  - cvxpy
  - ltbams
  - contextily
  - scienceplots